/* ============================================================
   AI-Driven Precision Agrochemical Sprayer - Language / i18n system
   Supports: English (en), Hindi (hi), Marathi (mr)
   ============================================================ */

const I18N = {
  en: {
    app_name: "AI-Driven Precision Agrochemical Sprayer",
    tagline: "AI-Driven Precision Agriculture",

    // Common
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    settings: "Settings",
    logout: "Logout",
    confirm: "Confirm",
    loading: "Loading...",

    // Language selection
    choose_language: "Choose Language",
    english: "English",
    hindi: "हिन्दी",
    hindi_name: "हिंदी",
    marathi: "मराठी",
    marathi_name: "मराठी",

    // Auth
    welcome: "Welcome",
    login: "Login",
    register: "Register",
    farmer_name: "Farmer Name",
    mobile_number: "Mobile Number",
    mobile_placeholder: "10-digit mobile number",
    password: "Password",
    remember_me: "Remember Me",
    show_hide: "Show/Hide",
    create_account: "Create Account",
    already_account: "Already have an account? Login",
    no_account: "New farmer? Register",
    login_success: "Logged in successfully!",
    register_success: "Account created successfully! Please login.",
    auth_failed: "Invalid mobile number or password.",
    logged_out: "You have been logged out.",

    // Dashboard
    dashboard: "Dashboard",
    welcome_farmer: "Welcome,",
    total_scanned: "Total Scanned",
    healthy_plants: "Healthy",
    diseased_plants: "Diseased",
    unknown_stats: "Unknown",
    scanned_today: "Scans Today",
    system_status: "System Status",
    mobile_camera: "Mobile Camera",
    readystatus: "READY",
    ai_model: "AI Model",
    scan_a_plant: "SCAN A PLANT",
    no_data_yet: "No scans yet. Scan your first plant!",

    // Scanner
    scan: "Scan",
    scanner: "Plant Scanner",
    take_photo: "Take Photo",
    take_photo_use: "Take Photo (rear camera)",
    upload_gallery: "Upload From Gallery",
    preview: "Preview",
    analyze_plant: "Analyze Plant",
    retake: "Retake Photo",
    analyzing: "Analyzing...",
    capturing: "Please allow camera access.",
    select_image_first: "Please take or select an image first.",

    // Result
    healthy_plant: "HEALTHY PLANT",
    plant_is_healthy: "PLANT IS HEALTHY",
    disease_detected: "DISEASE DETECTED",
    not_a_plant: "NOT A PLANT",
    unknown_plant: "UNKNOWN PLANT",
    unsupported_crop: "UNSUPPORTED CROP",
    analysis_not_available: "ANALYSIS NOT AVAILABLE",
    low_confidence: "LOW CONFIDENCE",
    unknown_plant_title: "UNKNOWN PLANT / LOW CONFIDENCE",
    unknown_plant_message: "Unable to confidently identify this image. Please scan a clear image of a supported plant leaf.",
    raw_class_debug: "Raw model output (debug only):",
    not_plant_message: "Please scan a clear image of a plant or leaf.",
    unknown_status_message: "Unable to confidently identify this plant. Please capture a clearer image.",
    unsupported_crop_message: "Disease detection is not currently available for this crop.",
    analysis_not_available_message: "Unable to reliably determine the health condition of this plant with the currently supported AI models.",
    pipeline_stopped: "Pipeline stopped at Plant Validation - identification was not attempted.",
    plant_name: "Plant / Crop Name",
    plant_crop: "Plant/Crop",
    plant_confidence: "Plant Confidence",
    plant_validation_confidence: "Plant Validation Confidence",
    plant_identification_confidence: "Plant Identification Confidence",
    health_status: "Health Status",
    health_status_healthy: "HEALTHY",
    health_status_diseased: "DISEASED",
    health_result: "Health Result",
    plant_health_analysis: "Plant Health Analysis",
    spray_decision: "Spray Decision Support",
    original_photo: "Original Photo",
    ai_overlay: "AI Overlay",
    stage_segmentation: "Health Segmentation",
    disease_detection_confidence: "Disease Detection Confidence",
    no_disease_symptoms: "No significant disease symptoms were detected.",
    affected_leaf_area: "Affected Leaf Area",
    severity_unavailable_message: "Severity could not be reliably calculated from the current image.",
    detection_overlay: "AI Detection Overlay",
    overlay_caption: "Red highlight = affected region detected by real leaf-area segmentation.",
    crop_name: "Crop Name",
    disease_name: "Disease Name",
    disease_confidence: "Disease Confidence",
    health_analysis_confidence: "Health Analysis Confidence",
    severity_label: "Severity",
    severity_unavailable: "Severity analysis unavailable",
    severity_low: "Low",
    severity_medium: "Medium",
    severity_high: "High",
    stage_validator: "Plant / Leaf Validation",
    stage_identifier: "Plant Identification",
    stage_disease: "Disease Detection",
    stage_severity: "Severity Analysis",
    stage_result: "Pipeline Analysis",
    confidence: "Confidence",
    detection_time: "Detection Time",
    no_disease_msg: "No disease detected.",
    disease_msg: "Disease detected. Targeted inspection or spraying may be required.",
    unknown_msg: "Unable to confidently identify the plant condition. Please capture a clearer image.",
    save_to_history: "Saved to scan history",
    pesticide_warning: "Note: AI assists decision-making on where to inspect/spray. Always follow agricultural recommendations for pesticide ratios.",

    // History
    history: "Scan History",
    filter_crop: "Filter by crop",
    all_crops: "All Crops",
    status_all: "All",
    status_healthy: "Healthy",
    status_diseased: "Diseased",
    status_unknown: "Unknown",
    clear_history: "Clear History",
    history_empty: "No scan history yet.",
    clear_confirm: "Clear all scan history? This cannot be undone.",

    // Analytics
    analytics: "Analytics",
    total_scans: "Total Scans",
    healthy_pct: "Healthy",
    diseased_pct: "Diseased",
    unknown_pct: "Unknown",
    most_detected_crop: "Most Detected Crop",
    disease_distribution: "Disease Distribution",
    crop_distribution: "Crop Distribution",
    no_analytics_data: "No data yet. Scan plants to see analytics.",

    // Settings
    change_language: "Change Language",
    notifications: "Notification Settings",
    notifications_enable: "Enable notifications",
    profile: "Profile",
    farmer_profile: "Farmer Profile",
    ai_model_status: "AI Model Status",
    backend_url: "Backend API URL",
    backend_url_placeholder: "http://192.168.1.100:5000",
    confidence_threshold: "Confidence Threshold",
    threshold_hint: "Below the gate the pipeline stops honestly (Low Plant Confidence / Analysis Not Available) - it never guesses a result.",
    clear_scan_history: "Clear Scan History",
    ai_status_loaded: "Model loaded and ready",
    backend_test: "Test Connection",
    backend_saved: "Backend URL saved.",
    profile_saved: "Profile updated.",
    notifications_enabled: "Notifications enabled.",
    notifications_disabled: "Notifications disabled.",

    // Error / misc
    error: "Error",
    network_error: "Cannot reach the AI backend. Check the Backend API URL in Settings and ensure the laptop server is running.",
    cannot_connect: "Unable to connect to the AI analysis server. Please check that the server is running and that your phone and computer are connected to the same network.",
    unknown: "Unknown",
    healthy: "Healthy",
    diseased: "Diseased",
    low_conf_filter: "Unknown",
    all: "All",
    crops: "Crops",
    no_supported_crops: "No crops loaded from the model.",
    not_logged_in: "Please login first.",
    _footer: "AI-Driven Precision Agrochemical Sprayer - Engineering Project | ESP32-CAM rover ready",
  },

  hi: {
    app_name: "AI-आधारित सटीक कृषि रासायनिक छिड़काव प्रणाली",
    tagline: "AI-आधारित सटीक कृषि",

    back: "वापस",
    save: "सेव",
    cancel: "रद्द",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    confirm: "पुष्टि",
    loading: "लोड हो रहा है...",

    choose_language: "भाषा चुनें",
    english: "अंग्रेज़ी",
    hindi_name: "हिंदी",
    marathi_name: "मराठी",

    welcome: "स्वागत है",
    login: "लॉग इन",
    register: "पंजीकरण",
    farmer_name: "किसान का नाम",
    mobile_number: "मोबाइल नंबर",
    mobile_placeholder: "10 अंकों का मोबाइल नंबर",
    password: "पासवर्ड",
    remember_me: "मुझे याद रखें",
    show_hide: "दिखाएं/छिपाएं",
    create_account: "खाता बनाएं",
    already_account: "पहले से खाता है? लॉग इन",
    no_account: "नए किसान? पंजीकरण करें",
    login_success: "सफलतापूर्वक लॉग इन किया!",
    register_success: "खाता बन गया! कृपया लॉग इन करें।",
    auth_failed: "गलत मोबाइल नंबर या पासवर्ड।",
    logged_out: "आप लॉग आउट हो गए हैं।",

    dashboard: "डैशबोर्ड",
    welcome_farmer: "स्वागत है,",
    total_scanned: "कुल स्कैन",
    healthy_plants: "स्वस्थ",
    diseased_plants: "रोगग्रस्त",
    unknown_stats: "अनजान",
    scanned_today: "आज के स्कैन",
    system_status: "सिस्टम स्थिति",
    mobile_camera: "मोबाइल कैमरा",
    readystatus: "तैयार",
    ai_model: "AI मॉडल",
    scan_a_plant: "पौधा स्कैन करें",
    no_data_yet: "अभी कोई स्कैन नहीं। अपना पहला पौधा स्कैन करें!",

    scan: "स्कैन",
    scanner: "पौधा स्कैनर",
    take_photo: "फोटो लें",
    take_photo_use: "फोटो लें (रियर कैमरा)",
    upload_gallery: "गैलरी से अपलोड करें",
    preview: "पूर्वावलोकन",
    analyze_plant: "पौधे का विश्लेषण करें",
    retake: "फिर से फोटो लें",
    analyzing: "विश्लेषण हो रहा है...",
    capturing: "कृपया कैमरा एक्सेस दें।",
    select_image_first: "कृपया पहले फोटो लें या चुनें।",

    healthy_plant: "स्वस्थ पौधा",
    plant_is_healthy: "पौधा स्वस्थ है",
    disease_detected: "रोग पाया गया",
    not_a_plant: "पौधा नहीं",
    unknown_plant: "अज्ञात पौधा",
    unsupported_crop: "असमर्थित फसल",
    analysis_not_available: "विश्लेषण उपलब्ध नहीं",
    low_confidence: "कम विश्वास",
    unknown_plant_title: "अज्ञात पौधा / कम विश्वास",
    unknown_plant_message: "इस छवि को निश्चित रूप से पहचाना नहीं जा सका। कृपया किसी समर्थित पौधे की पत्ती की साफ़ छवि स्कैन करें।",
    raw_class_debug: "मॉडल का कच्चा आउटपुट (केवल डीबग):",
    not_plant_message: "कृपया पौधे या पत्ती की साफ़ छवि स्कैन करें।",
    unknown_status_message: "इस पौधे की निश्चित रूप से पहचान नहीं हो सकी। कृपया साफ़ छवि लें।",
    unsupported_crop_message: "इस फसल के लिए रोग पहचान अभी उपलब्ध नहीं है।",
    analysis_not_available_message: "वर्तमान में समर्थित AI मॉडलों के साथ इस पौधे की स्वास्थ्य स्थिति का विश्वसनीय निर्धारण संभव नहीं है।",
    pipeline_stopped: "पाइपलाइन पौधा सत्यापन पर रुक गई - पहचान नहीं की गई।",
    plant_name: "पौधे / फसल का नाम",
    plant_crop: "पौधा/फसल",
    plant_confidence: "पौधा पहचान विश्वास",
    plant_validation_confidence: "पौधा सत्यापन विश्वास",
    plant_identification_confidence: "पौधा पहचान विश्वास",
    health_status: "स्वास्थ्य स्थिति",
    health_status_healthy: "स्वस्थ",
    health_status_diseased: "रोगग्रस्त",
    health_result: "स्वास्थ्य परिणाम",
    plant_health_analysis: "पौधे का स्वास्थ्य विश्लेषण",
    spray_decision: "छिड़काव निर्णय सहायता",
    original_photo: "मूल फोटो",
    ai_overlay: "AI ओव्हरले",
    stage_segmentation: "स्वास्थ्य विभाजन",
    disease_detection_confidence: "रोग पहचान विश्वास",
    no_disease_symptoms: "कोई महत्वपूर्ण रोग लक्षण नहीं पाए गए।",
    affected_leaf_area: "प्रभावित पत्ती क्षेत्र",
    severity_unavailable_message: "वर्तमान छवि से गंभीरता की विश्वसनीय गणना संभव नहीं है।",
    detection_overlay: "AI पहचान ओवरले",
    overlay_caption: "लाल हाइलाइट = वास्तविक पत्ती-क्षेत्र विभाजन से पहचाना गया प्रभावित क्षेत्र।",
    crop_name: "फसल का नाम",
    disease_name: "रोग का नाम",
    disease_confidence: "रोग पहचान विश्वास",
    health_analysis_confidence: "स्वास्थ्य विश्लेषण विश्वास",
    severity_label: "गंभीरता",
    severity_unavailable: "गंभीरता विश्लेषण उपलब्ध नहीं",
    severity_low: "कम",
    severity_medium: "मध्यम",
    severity_high: "उच्च",
    stage_validator: "पौधा/पत्ती सत्यापन",
    stage_identifier: "पौधा पहचान",
    stage_disease: "रोग पहचान",
    stage_severity: "गंभीरता विश्लेषण",
    stage_result: "पाइपलाइन विश्लेषण",
    confidence: "विश्वास",
    detection_time: "पहचान का समय",
    no_disease_msg: "कोई रोग नहीं मिला।",
    disease_msg: "रोग मिला। लक्षित जांच या छिड़काव आवश्यक हो सकता है।",
    unknown_msg: "पौधे की स्थिति निश्चित रूप से पहचानी नहीं जा सकी। कृपया साफ़ छवि लें।",
    save_to_history: "स्कैन इतिहास में सेव किया गया",
    pesticide_warning: "नोट: AI केवल यह तय करने में मदद करता है कि कहां जांच/छिड़काव करना है। कीटनाशक अनुपात के लिए हमेशा कृषि सिफारिशों का पालन करें।",

    history: "स्कैन इतिहास",
    filter_crop: "फसल के अनुसार फ़िल्टर",
    all_crops: "सभी फसलें",
    status_all: "सभी",
    status_healthy: "स्वस्थ",
    status_diseased: "रोगग्रस्त",
    status_unknown: "अनजान",
    clear_history: "इतिहास साफ़ करें",
    history_empty: "अभी कोई स्कैन इतिहास नहीं है।",
    clear_confirm: "पूरा स्कैन इतिहास साफ़ करें? इसे पूर्ववत नहीं किया जा सकता।",

    analytics: "विश्लेषण",
    total_scans: "कुल स्कैन",
    healthy_pct: "स्वस्थ",
    diseased_pct: "रोगग्रस्त",
    unknown_pct: "अनजान",
    most_detected_crop: "सबसे अधिक पहचानी गई फसल",
    disease_distribution: "रोग वितरण",
    crop_distribution: "फसल वितरण",
    no_analytics_data: "अभी कोई डेटा नहीं। विश्लेषण के लिए पौधे स्कैन करें।",

    change_language: "भाषा बदलें",
    notifications: "सूचना सेटिंग्स",
    notifications_enable: "सूचनाएं सक्षम करें",
    profile: "प्रोफ़ाइल",
    farmer_profile: "किसान प्रोफ़ाइल",
    ai_model_status: "AI मॉडल स्थिति",
    backend_url: "बैकएंड API URL",
    backend_url_placeholder: "http://192.168.1.100:5000",
    confidence_threshold: "विश्वास सीमा",
    threshold_hint: "यदि इस गेट से कम विश्वास है तो पाइपलाइन ईमानदारी से रुकती है (कम विश्वास / विश्लेषण उपलब्ध नहीं) - परिणाम अनुमान से नहीं बताया जाता।",
    clear_scan_history: "स्कैन इतिहास साफ़ करें",
    ai_status_loaded: "मॉडल लोड और तैयार है",
    backend_test: "कनेक्शन जांचें",
    backend_saved: "बैकएंड URL सेव हो गया।",
    profile_saved: "प्रोफ़ाइल अपडेट हुई।",
    notifications_enabled: "सूचनाएं सक्षम।",
    notifications_disabled: "सूचनाएं अक्षम।",

    error: "त्रुटि",
    network_error: "AI बैकएंड तक नहीं पहुंच सके। सेटिंग्स में बैकएंड API URL जांचें और सुनिश्चित करें कि लैपटॉप सर्वर चालू है।",
    cannot_connect: "AI विश्लेषण सर्वर से कनेक्ट नहीं हो सका। कृपया जांचें कि सर्वर चालू है और आपका फ़ोन तथा कंप्यूटर एक ही नेटवर्क से जुड़े हैं।",
    unknown: "अनजान",
    healthy: "स्वस्थ",
    diseased: "रोगग्रस्त",
    low_conf_filter: "अनजान",
    all: "सभी",
    crops: "फसलें",
    no_supported_crops: "मॉडल से कोई फसल लोड नहीं हुई।",
    not_logged_in: "कृपया पहले लॉग इन करें।",
    _footer: "AI-आधारित सटीक कृषि रासायनिक छिड़काव प्रणाली - इंजीनियरिंग प्रोजेक्ट | ESP32-CAM रोवर के लिए तैयार",
  },

  mr: {
    app_name: "AI-आधारित अचूक कृषी रासायनिक फवारणी प्रणाली",
    tagline: "AI-आधारित अचूक कृषी",

    back: "मागे",
    save: "सेव्ह",
    cancel: "रद्द",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    confirm: "पुष्टी",
    loading: "लोड होत आहे...",

    choose_language: "भाषा निवडा",
    english: "इंग्रजी",
    hindi_name: "हिंदी",
    marathi_name: "मराठी",

    welcome: "स्वागत आहे",
    login: "लॉग इन",
    register: "नोंदणी",
    farmer_name: "शेतकरीाचे नाव",
    mobile_number: "मोबाईल क्रमांक",
    mobile_placeholder: "10 अंकी मोबाईल क्रमांक",
    password: "पासवर्ड",
    remember_me: "लक्षात ठेवा",
    show_hide: "दाखवा/लपवा",
    create_account: "खाते तयार करा",
    already_account: "आधीच खाते आहे? लॉग इन",
    no_account: "नवीन शेतकरी? नोंदणी करा",
    login_success: "यशस्वीरित्या लॉग इन झाले!",
    register_success: "खाते तयार झाले! कृपया लॉग इन करा.",
    auth_failed: "चुकीचा मोबाईल क्रमांक किंवा पासवर्ड.",
    logged_out: "तुम्ही लॉग आउट झाला आहात.",

    dashboard: "डॅशबोर्ड",
    welcome_farmer: "स्वागत आहे,",
    total_scanned: "एकूण स्कॅन",
    healthy_plants: "निरोगी",
    diseased_plants: "रोगग्रस्त",
    unknown_stats: "अज्ञात",
    scanned_today: "आजचे स्कॅन",
    system_status: "प्रणाली स्थिती",
    mobile_camera: "मोबाईल कॅमेरा",
    readystatus: "तयार",
    ai_model: "AI मॉडेल",
    scan_a_plant: "वनस्पती स्कॅन करा",
    no_data_yet: "अजून स्कॅन नाही. पहिली वनस्पती स्कॅन करा!",

    scan: "स्कॅन",
    scanner: "वनस्पती स्कॅनर",
    take_photo: "फोटो घ्या",
    take_photo_use: "फोटो घ्या (मागील कॅमेरा)",
    upload_gallery: "गॅलरीतून अपलोड करा",
    preview: "पूर्वावलोकन",
    analyze_plant: "वनस्पतीचे विश्लेषण करा",
    retake: "पुन्हा फोटो घ्या",
    analyzing: "विश्लेषण होत आहे...",
    capturing: "कृपया कॅमेरा परवानगी द्या.",
    select_image_first: "कृपया प्रथम फोटो घ्या किंवा निवडा.",

    healthy_plant: "निरोगी वनस्पती",
    plant_is_healthy: "वनस्पती निरोगी आहे",
    disease_detected: "रोग आढळला",
    not_a_plant: "वनस्पती नाही",
    unknown_plant: "अज्ञात वनस्पती",
    unsupported_crop: "असमर्थित पीक",
    analysis_not_available: "विश्लेषण उपलब्ध नाही",
    low_confidence: "कमी आत्मविश्वास",
    unknown_plant_title: "अज्ञात वनस्पती / कमी आत्मविश्वास",
    unknown_plant_message: "या प्रतिमेची निश्चितपणे ओळख झाली नाही. कृपया समर्थित वनस्पतीच्या पानाची स्पष्ट प्रतिमा स्कॅन करा.",
    raw_class_debug: "मॉडेलचे कच्चे आउटपुट (फक्त डीबग):",
    not_plant_message: "कृपया वनस्पती किंवा पानाची स्पष्ट प्रतिमा स्कॅन करा.",
    unknown_status_message: "या वनस्पतीची निश्चित ओळख झाली नाही. कृपया स्पष्ट प्रतिमा घ्या.",
    unsupported_crop_message: "या पिकासाठी रोग ओळख सध्या उपलब्ध नाही.",
    analysis_not_available_message: "सध्या समर्थित AI मॉडेल्सद्वारे या वनस्पतीच्या आरोग्य स्थितीचे विश्वसनीय निर्धारण शक्य नाही.",
    pipeline_stopped: "पाइपलाइन वनस्पती सत्यापनावर थांबली - ओळख केली नाही.",
    plant_name: "वनस्पती / पिकाचे नाव",
    plant_crop: "वनस्पती/पीक",
    plant_confidence: "वनस्पती ओळख आत्मविश्वास",
    plant_validation_confidence: "वनस्पती सत्यापन आत्मविश्वास",
    plant_identification_confidence: "वनस्पती ओळख आत्मविश्वास",
    health_status: "आरोग्य स्थिती",
    health_status_healthy: "निरोगी",
    health_status_diseased: "रोगग्रस्त",
    health_result: "आरोग्य परिणाम",
    plant_health_analysis: "वनस्पती आरोग्य विश्लेषण",
    spray_decision: "फवारणी निर्णय सहायता",
    original_photo: "मूळ फोटो",
    ai_overlay: "AI ओव्हरले",
    stage_segmentation: "आरोग्य विभाजन",
    disease_detection_confidence: "रोग ओळख आत्मविश्वास",
    no_disease_symptoms: "रोगाची कोणतीही महत्त्वाची लक्षणे आढळली नाहीत.",
    affected_leaf_area: "प्रभावित पानाचे क्षेत्र",
    severity_unavailable_message: "सध्याच्या प्रतिमेवरून तीव्रतेची विश्वसनीय गणना शक्य नाही.",
    detection_overlay: "AI ओळख ओव्हरले",
    overlay_caption: "लाल हायलाइट = वास्तविक पान-क्षेत्र विभाजनाने ओळखलेला प्रभावित भाग.",
    crop_name: "पिकाचे नाव",
    disease_name: "रोगाचे नाव",
    disease_confidence: "रोग ओळख आत्मविश्वास",
    health_analysis_confidence: "आरोग्य विश्लेषण आत्मविश्वास",
    severity_label: "तीव्रता",
    severity_unavailable: "तीव्रता विश्लेषण उपलब्ध नाही",
    severity_low: "कमी",
    severity_medium: "मध्यम",
    severity_high: "उच्च",
    stage_validator: "वनस्पती/पान सत्यापन",
    stage_identifier: "वनस्पती ओळख",
    stage_disease: "रोग ओळख",
    stage_severity: "तीव्रता विश्लेषण",
    stage_result: "पाइपलाइन विश्लेषण",
    confidence: "आत्मविश्वास",
    detection_time: "ओळखीची वेळ",
    no_disease_msg: "कोणताही रोग आढळला नाही.",
    disease_msg: "रोग आढळला. लक्ष्यित तपासणी किंवा फवारणी आवश्यक असू शकते.",
    unknown_msg: "वनस्पतीची स्थिती निश्चितपणे ओळखता आली नाही. कृपया स्वच्छ प्रतिमा घ्या.",
    save_to_history: "स्कॅन इतिहासात सेव्ह झाले",
    pesticide_warning: "टीप: AI फक्त कुठे तपासायचे/फवारायचे हे ठरवण्यात मदत करते. कीटकनाशक प्रमाणासाठी नेहमी कृषी शिफारशींचे पालन करा.",

    history: "स्कॅन इतिहास",
    filter_crop: "पिकानुसार फिल्टर",
    all_crops: "सर्व पिके",
    status_all: "सर्व",
    status_healthy: "निरोगी",
    status_diseased: "रोगग्रस्त",
    status_unknown: "अज्ञात",
    clear_history: "इतिहास साफ करा",
    history_empty: "अजून स्कॅन इतिहास नाही.",
    clear_confirm: "संपूर्ण स्कॅन इतिहास साफ करायचा? ते पूर्ववत होणार नाही.",

    analytics: "विश्लेषण",
    total_scans: "एकूण स्कॅन",
    healthy_pct: "निरोगी",
    diseased_pct: "रोगग्रस्त",
    unknown_pct: "अज्ञात",
    most_detected_crop: "सर्वाधिक आढळलेले पीक",
    disease_distribution: "रोग वितरण",
    crop_distribution: "पीक वितरण",
    no_analytics_data: "अजून डेटा नाही. विश्लेषणासाठी वनस्पती स्कॅन करा.",

    change_language: "भाषा बदला",
    notifications: "सूचना सेटिंग्ज",
    notifications_enable: "सूचना सक्षम करा",
    profile: "प्रोफाइल",
    farmer_profile: "शेतकरी प्रोफाइल",
    ai_model_status: "AI मॉडेल स्थिती",
    backend_url: "बॅकएंड API URL",
    backend_url_placeholder: "http://192.168.1.100:5000",
    confidence_threshold: "आत्मविश्वासाची मर्यादा",
    threshold_hint: "AI आत्मविश्वास या गेटच्या खाली असल्यास पाइपलाइन प्रामाणिकपणे थांबते (कमी आत्मविश्वास / विश्लेषण उपलब्ध नाही) - अंदाज घेतला जात नाही.",
    clear_scan_history: "स्कॅन इतिहास साफ करा",
    ai_status_loaded: "मॉडेल लोड आणि तयार आहे",
    backend_test: "कनेक्शन तपासा",
    backend_saved: "बॅकएंड URL सेव्ह झाला.",
    profile_saved: "प्रोफाइल अपडेट झाली.",
    notifications_enabled: "सूचना सक्षम.",
    notifications_disabled: "सूचना अक्षम.",

    error: "त्रुटी",
    network_error: "AI बॅकएंडपर्यंत पोहोचू शकलो नाही. सेटिंग्जमध्ये बॅकएंड API URL तपासा आणि लॅपटॉप सर्व्हर चालू असल्याचे सुनिश्चित करा.",
    cannot_connect: "AI विश्लेषण सर्व्हरशी कनेक्ट होऊ शकले नाही. सर्व्हर चालू असल्याचे आणि तुमचा फोन व संगणक एकाच नेटवर्कवर असल्याचे कृपया तपासा.",
    unknown: "अज्ञात",
    healthy: "निरोगी",
    diseased: "रोगग्रस्त",
    low_conf_filter: "अज्ञात",
    all: "सर्व",
    crops: "पिके",
    no_supported_crops: "मॉडेलमधून कोणतीही पिके लोड झाली नाहीत.",
    not_logged_in: "कृपया प्रथम लॉग इन करा.",
    _footer: "AI-आधारित अचूक कृषी रासायनिक फवारणी प्रणाली - अभियांत्रिकी प्रोजेक्ट | ESP32-CAM रोव्हरसाठी तयार",
  },
};

/* ---------- helpers ---------- */
const Lang = {
  get current() {
    return localStorage.getItem("AI-Driven Precision Agrochemical Sprayer_lang") || "en";
  },

  set(lang) {
    localStorage.setItem("AI-Driven Precision Agrochemical Sprayer_lang", lang);
    document.documentElement.lang = lang;
  },

  key(k) {
    const dict = I18N[this.current] || I18N.en;
    return dict[k] !== undefined ? dict[k] : (I18N.en[k] !== undefined ? I18N.en[k] : k);
  },

  /* Apply translation to elements marked [data-i18n] and input placeholders */
  apply(root = document) {
    root.querySelectorAll("[data-i18n]").forEach(el => {
      const k = el.getAttribute("data-i18n");
      el.textContent = Lang.key(k);
      el.classList.add("translated");
    });
    root.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
      const k = el.getAttribute("data-i18n-placeholder");
      el.setAttribute("placeholder", Lang.key(k));
      el.classList.add("translated");
    });
  },

  onReady() {
    document.documentElement.lang = this.current;
    this.apply();
  },
};

/* auto-run */
if (typeof document !== "undefined") {
  document.addEventListener("DOMContentLoaded", () => Lang.onReady());
}